language: node_js
node_js:
- '10'

before_install:
- openssl aes-256-cbc -K $encrypted_b448b3ab5bbb_key -iv $encrypted_b448b3ab5bbb_iv
  -in deploy_rsa.enc -out $TRAVIS_BUILD_DIR/deploy_rsa -d

script:
- ssh-keyscan -H lingvomake.ml >> ~/.ssh/known_hosts
#- npm run build

after_success:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
- scp -o "StrictHostKeyChecking=no" -i ./deploy_rsa -r ../lingvomake root@lingvomake.ml:/home/Projects/deploy
- ssh -o "StrictHostKeyChecking=no" -i ./deploy_rsa root@lingvomake.ml 'cd /home/Projects/deploy/lingvomake/; npm run build'

branches:
  only:
  - deploy
